"""add timestamp to lots

Revision ID: 3410c3c74409
Revises: aa78ae309ca6
Create Date: 2018-05-14 11:12:59.793993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3410c3c74409'
down_revision = 'aa78ae309ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_lot_timestamp'), 'lot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_timestamp'), table_name='lot')
    op.drop_column('lot', 'timestamp')
    # ### end Alembic commands ###
